version: '3'
services:
  postgres:
    image: mdillon/postgis:latest
    hostname: postgres
    volumes:
      - .:/usr/app/geoscoot
  web:
    build:
      context: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app:delegated
    ports:
      - "3000:3000"
    depends_on:
      - postgres
